# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75feec98d05e1562887bc10c7ba2e838a0099aa98ada6a7aacfa4716c0582a2c6eb618d2456a90496b7bd5dde517dbaaaa5fc22e8ed34fb48828db57a825a3e9

test:
  secret_key_base: 5e72fff5fe480c9e4eeebd4c989bf9c6aed83c79338b7d6792549809af9063393372ebd1a0187da3a0aa9728cf8c68c981166f65ff385e8cd32fe81f530112aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
